app = "pigeonmq-demo-broker"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8787"
  PIGEON_DATA_DIR = "/data"

[[mounts]]
  source = "pigeon_data"
  destination = "/data"

[http_service]
  internal_port = 8787
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
